"""enrollment tables

Revision ID: 4f96b3d2c5ff
Revises: b1ee6f6e4b3c
Create Date: 2026-06-24 02:48:44.480607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f96b3d2c5ff'
down_revision: Union[str, None] = 'b1ee6f6e4b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_codes_code'), 'enrollment_codes', ['code'], unique=True)
    op.create_index(op.f('ix_enrollment_codes_hospital_id'), 'enrollment_codes', ['hospital_id'], unique=False)
    op.create_table('hospital_enrollments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='enrollmentstatus'), nullable=False),
    sa.Column('initiated_by', sa.Enum('patient', 'code', 'hospital', name='enrollmentinitiatedby'), nullable=False),
    sa.Column('code_used', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_enrollments_hospital_id'), 'hospital_enrollments', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_hospital_enrollments_patient_id'), 'hospital_enrollments', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hospital_enrollments_patient_id'), table_name='hospital_enrollments')
    op.drop_index(op.f('ix_hospital_enrollments_hospital_id'), table_name='hospital_enrollments')
    op.drop_table('hospital_enrollments')
    op.drop_index(op.f('ix_enrollment_codes_hospital_id'), table_name='enrollment_codes')
    op.drop_index(op.f('ix_enrollment_codes_code'), table_name='enrollment_codes')
    op.drop_table('enrollment_codes')
    # ### end Alembic commands ###
