"""baseline full schema

Revision ID: dbd95abe97c9
Revises: 
Create Date: 2026-06-23 23:01:50.049480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbd95abe97c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('education_content',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('video', 'audio', 'guide', 'infographic', name='contenttype'), nullable=False),
    sa.Column('topic', sa.Enum('understanding_heart', 'before_surgery', 'surgery_stay', 'recovery', 'living_well', name='contenttopic'), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('surgery_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('has_german_subtitles', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospitals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('postcode', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('hospital', 'rehab_centre', name='hospitaltype'), nullable=False),
    sa.Column('surgeon_message', sa.Text(), nullable=True),
    sa.Column('maps_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quizzes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('correct_index', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_quiz_id'), 'quiz_questions', ['quiz_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('patient', 'carer', 'clinician', 'admin', name='userrole'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('profile_photo_url', sa.String(), nullable=True),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('biometric_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('surgery_type', sa.Enum('cabg', 'valve', 'tavi', 'aortic', 'combined', 'none', name='surgerytype'), nullable=True),
    sa.Column('surgery_date', sa.Date(), nullable=True),
    sa.Column('hospital_id', sa.Uuid(), nullable=True),
    sa.Column('surgeon_name', sa.String(), nullable=True),
    sa.Column('nyha_class', sa.Enum('I', 'II', 'III', 'IV', name='nyhaclass'), nullable=True),
    sa.Column('diagnosis', sa.String(), nullable=True),
    sa.Column('current_phase', sa.Enum('diagnosis', 'preop', 'surgery', 'inpatient', 'rehab', 'thriving', name='phasekey'), nullable=False),
    sa.Column('journey_progress', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('active_minutes', sa.Integer(), nullable=True),
    sa.Column('walk_duration_sec', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('pain_high', 'mood_low_3day', 'fever', 'delirium', 'missed_dressing', 'missed_meds', 'wound_concern', 'symptom_report', 'abnormal_vital', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'warning', 'info', name='alertseverity'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_ref', sa.Uuid(), nullable=True),
    sa.Column('acked_by', sa.Uuid(), nullable=True),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['acked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_patient_id'), 'alerts', ['patient_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('hospital_id', sa.Uuid(), nullable=True),
    sa.Column('appointment_type', sa.Enum('followup', 'review', 'rehab', 'physio', 'telemedicine', name='appointmenttype'), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_user_id'), 'appointments', ['user_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_patient_id'), 'audit_log', ['patient_id'], unique=False)
    op.create_table('breathing_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_type', sa.Enum('spirometry', 'breathing', 'cough', name='breathingsessiontype'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('scheduled_slot', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breathing_sessions_user_id'), 'breathing_sessions', ['user_id'], unique=False)
    op.create_table('carer_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('carer_id', sa.Uuid(), nullable=True),
    sa.Column('invite_email', sa.String(), nullable=True),
    sa.Column('invite_token', sa.String(), nullable=True),
    sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'revoked', name='carerlinkstatus'), nullable=False),
    sa.Column('permissions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carer_links_carer_id'), 'carer_links', ['carer_id'], unique=False)
    op.create_index(op.f('ix_carer_links_invite_token'), 'carer_links', ['invite_token'], unique=False)
    op.create_index(op.f('ix_carer_links_patient_id'), 'carer_links', ['patient_id'], unique=False)
    op.create_table('cessation_tracking',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('smoking', 'alcohol', name='cessationtype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('current_streak_days', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cessation_tracking_user_id'), 'cessation_tracking', ['user_id'], unique=False)
    op.create_table('clinical_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('score_type', sa.Enum('gad7', 'phq9', 'pcl5', 'delirium', name='scoretype'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('severity', sa.Enum('minimal', 'mild', 'moderate', 'severe', name='severity'), nullable=True),
    sa.Column('administered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_week', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_scores_user_id'), 'clinical_scores', ['user_id'], unique=False)
    op.create_table('clinician_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clinician_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('clinician_role', sa.Enum('surgeon', 'nurse', 'physio', 'psychokardiologist', 'admin', name='clinicianrole'), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinician_assignments_clinician_id'), 'clinician_assignments', ['clinician_id'], unique=False)
    op.create_index(op.f('ix_clinician_assignments_patient_id'), 'clinician_assignments', ['patient_id'], unique=False)
    op.create_table('consent_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('consent_type', sa.Enum('terms', 'privacy', 'data_sharing', 'carer_visibility', name='consenttype'), nullable=False),
    sa.Column('consent_version', sa.String(), nullable=False),
    sa.Column('text_shown', sa.Text(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_log_user_id'), 'consent_log', ['user_id'], unique=False)
    op.create_table('content_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('resume_position_sec', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('favourited', sa.Boolean(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['education_content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_progress_content_id'), 'content_progress', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_progress_user_id'), 'content_progress', ['user_id'], unique=False)
    op.create_table('data_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('export', 'deletion', name='datarequesttype'), nullable=False),
    sa.Column('status', sa.Enum('requested', 'processing', 'complete', name='datarequeststatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('export_s3_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_requests_user_id'), 'data_requests', ['user_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('fcm_token', sa.String(), nullable=True),
    sa.Column('platform', sa.Enum('ios', 'android', name='platform'), nullable=True),
    sa.Column('biometric_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('eras_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('item_key', sa.Enum('smoking', 'nutrition', 'exercise', 'breathing', 'medications', 'skin_prep', 'education', name='erasitem'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eras_progress_user_id'), 'eras_progress', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('activity', 'recovery', 'return_to_work', 'custom', name='goaltype'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('target_value', sa.String(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('achieved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('habit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('habit', sa.Enum('medications', 'meals', 'activity', 'stress', 'sleep', name='habittype'), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_logs_user_id'), 'habit_logs', ['user_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('decision_goal', 'decision_concern', 'surgeon_question', 'gratitude', name='journaltype'), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('photo_s3_key', sa.String(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('shared_with_care_team', sa.Boolean(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.create_table('journey_phases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('phase_key', sa.Enum('diagnosis', 'preop', 'surgery', 'inpatient', 'rehab', 'thriving', name='phasekey'), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('completed', 'active', 'upcoming', name='phasestatus'), nullable=False),
    sa.Column('date_label', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_by', sa.Enum('auto', 'clinician', name='activatedby'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_phases_user_id'), 'journey_phases', ['user_id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dose', sa.String(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('times', sa.String(), nullable=True),
    sa.Column('is_anticoagulant', sa.Boolean(), nullable=False),
    sa.Column('stop_date', sa.Date(), nullable=True),
    sa.Column('bridge_protocol', sa.Text(), nullable=True),
    sa.Column('purpose_de', sa.Text(), nullable=True),
    sa.Column('phase', sa.Enum('diagnosis', 'preop', 'surgery', 'inpatient', 'rehab', 'thriving', name='phasekey'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_user_id'), 'medications', ['user_id'], unique=False)
    op.create_table('message_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clinician_role', sa.Enum('surgeon', 'nurse', 'physio', 'psychokardiologist', 'admin', name='clinicianrole'), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_threads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('care_team', 'physiotherapy', 'education', 'emotional_support', 'alerts', 'family', name='messagecategory'), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_threads_patient_id'), 'message_threads', ['patient_id'], unique=False)
    op.create_table('mobilisation_milestones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('milestone', sa.Enum('sitting', 'standing', 'first_walk', 'session', name='mobilisationmilestone'), nullable=False),
    sa.Column('target', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('achieved', sa.Boolean(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('set_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['set_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobilisation_milestones_user_id'), 'mobilisation_milestones', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('muted_categories', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('quiet_hours_start', sa.String(), nullable=False),
    sa.Column('quiet_hours_end', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('reminder', 'education', 'motivation', 'social', 'alert', 'critical', name='notificationcategory'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deep_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('nutrition_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('protein_grams', sa.Integer(), nullable=True),
    sa.Column('hydration_glasses', sa.Integer(), nullable=True),
    sa.Column('meals_count', sa.Integer(), nullable=True),
    sa.Column('bowel_movement', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_logs_user_id'), 'nutrition_logs', ['user_id'], unique=False)
    op.create_table('onboarding_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('step_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_progress_user_id'), 'onboarding_progress', ['user_id'], unique=False)
    op.create_table('patient_allergies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('allergy', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_allergies_user_id'), 'patient_allergies', ['user_id'], unique=False)
    op.create_table('patient_conditions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('onboarding', 'clinician', name='conditionsource'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_conditions_user_id'), 'patient_conditions', ['user_id'], unique=False)
    op.create_table('peer_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('matched_user_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('heart_buddy', 'mentor', name='peermatchtype'), nullable=False),
    sa.Column('surgery_type', sa.Enum('cabg', 'valve', 'tavi', 'aortic', 'combined', 'none', name='surgerytype'), nullable=True),
    sa.Column('age_band', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('opted_in', 'matched', 'left', name='peermatchstatus'), nullable=False),
    sa.Column('is_moderated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matched_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_matches_user_id'), 'peer_matches', ['user_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('answers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('audio', 'video', name='recordingtype'), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('for_carer_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['for_carer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_user_id'), 'recordings', ['user_id'], unique=False)
    op.create_table('recovery_checkins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('feeling', sa.String(), nullable=True),
    sa.Column('wound_issues', sa.Boolean(), nullable=False),
    sa.Column('pain_level', sa.Integer(), nullable=True),
    sa.Column('sleep_quality', sa.String(), nullable=True),
    sa.Column('concerns', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_checkins_user_id'), 'recovery_checkins', ['user_id'], unique=False)
    op.create_table('recovery_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('actual_progress', sa.Float(), nullable=True),
    sa.Column('expected_progress', sa.Float(), nullable=True),
    sa.Column('on_track_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_snapshots_user_id'), 'recovery_snapshots', ['user_id'], unique=False)
    op.create_table('rehab_enrollments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=True),
    sa.Column('program_overview', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('what_to_bring', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rehab_enrollments_user_id'), 'rehab_enrollments', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('discharge_summary', 'recovery', 'compliance', 'pain_mood', 'audit_export', name='reporttype'), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('date_range_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_range_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_patient_id'), 'reports', ['patient_id'], unique=False)
    op.create_table('return_to_work_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.Enum('desk', 'light_physical', 'heavy_physical', name='jobtype'), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_to_work_plans_user_id'), 'return_to_work_plans', ['user_id'], unique=False)
    op.create_table('stage_transitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('from_phase', sa.Enum('diagnosis', 'preop', 'surgery', 'inpatient', 'rehab', 'thriving', name='phasekey'), nullable=True),
    sa.Column('to_phase', sa.Enum('diagnosis', 'preop', 'surgery', 'inpatient', 'rehab', 'thriving', name='phasekey'), nullable=False),
    sa.Column('trigger', sa.Enum('auto_date', 'clinician', name='transitiontrigger'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_transitions_user_id'), 'stage_transitions', ['user_id'], unique=False)
    op.create_table('surgery_checklist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('item_key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.Enum('fasting', 'cho', 'preparation', name='surgerychecklistcategory'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surgery_checklist_user_id'), 'surgery_checklist', ['user_id'], unique=False)
    op.create_table('symptom_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('symptom', sa.Enum('incision_redness', 'fever', 'increased_pain', 'breathlessness', 'wound_oozing', name='symptomtype'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptom_reports_user_id'), 'symptom_reports', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('breathing', 'activity', 'nutrition', 'hydration', 'medication', 'sleep', 'emotional', 'education', 'wound', 'appointment', name='taskcategory'), nullable=True),
    sa.Column('scheduled_time', sa.String(), nullable=True),
    sa.Column('time_color', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('task_date', sa.String(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('theatre_status_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('event', sa.Enum('checked_in', 'anaesthesia', 'surgery_start', 'surgery_complete', 'recovery', 'on_ward', name='theatreevent'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theatre_status_events_patient_id'), 'theatre_status_events', ['patient_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('badge_id', sa.Uuid(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_badges_badge_id'), 'user_badges', ['badge_id'], unique=False)
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.create_table('vitals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('pain_rest', 'pain_cough', 'pain_move', 'mood', 'spo2', 'heart_rate', 'bp_systolic', 'bp_diastolic', 'weight', 'temperature', 'steps', name='vitaltype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('manual', 'wearable', name='vitalsource'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vitals_user_id'), 'vitals', ['user_id'], unique=False)
    op.create_table('wearable_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('apple_health', 'google_health', 'fitbit', 'garmin', name='wearableprovider'), nullable=False),
    sa.Column('status', sa.Enum('connected', 'disconnected', name='wearablestatus'), nullable=False),
    sa.Column('oauth_tokens', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wearable_connections_user_id'), 'wearable_connections', ['user_id'], unique=False)
    op.create_table('wearable_readings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('metric', sa.Enum('heart_rate', 'steps', 'sleep', 'spo2', 'hrv', 'ecg', 'active_energy', name='wearablemetric'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wearable_readings_user_id'), 'wearable_readings', ['user_id'], unique=False)
    op.create_table('wound_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('day_post_op', sa.Integer(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nurse_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wound_photos_user_id'), 'wound_photos', ['user_id'], unique=False)
    op.create_table('medication_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('medication_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('taken', 'missed', 'skipped', name='medicationlogstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_logs_medication_id'), 'medication_logs', ['medication_id'], unique=False)
    op.create_index(op.f('ix_medication_logs_user_id'), 'medication_logs', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=True),
    sa.Column('sender_role', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('attachment_s3_key', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['message_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('referred_to_role', sa.String(), nullable=True),
    sa.Column('trigger_score_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'scheduled', name='referralstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trigger_score_id'], ['clinical_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_patient_id'), 'referrals', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referrals_patient_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_medication_logs_user_id'), table_name='medication_logs')
    op.drop_index(op.f('ix_medication_logs_medication_id'), table_name='medication_logs')
    op.drop_table('medication_logs')
    op.drop_index(op.f('ix_wound_photos_user_id'), table_name='wound_photos')
    op.drop_table('wound_photos')
    op.drop_index(op.f('ix_wearable_readings_user_id'), table_name='wearable_readings')
    op.drop_table('wearable_readings')
    op.drop_index(op.f('ix_wearable_connections_user_id'), table_name='wearable_connections')
    op.drop_table('wearable_connections')
    op.drop_index(op.f('ix_vitals_user_id'), table_name='vitals')
    op.drop_table('vitals')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_badge_id'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_theatre_status_events_patient_id'), table_name='theatre_status_events')
    op.drop_table('theatre_status_events')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_symptom_reports_user_id'), table_name='symptom_reports')
    op.drop_table('symptom_reports')
    op.drop_index(op.f('ix_surgery_checklist_user_id'), table_name='surgery_checklist')
    op.drop_table('surgery_checklist')
    op.drop_index(op.f('ix_stage_transitions_user_id'), table_name='stage_transitions')
    op.drop_table('stage_transitions')
    op.drop_index(op.f('ix_return_to_work_plans_user_id'), table_name='return_to_work_plans')
    op.drop_table('return_to_work_plans')
    op.drop_index(op.f('ix_reports_patient_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_rehab_enrollments_user_id'), table_name='rehab_enrollments')
    op.drop_table('rehab_enrollments')
    op.drop_index(op.f('ix_recovery_snapshots_user_id'), table_name='recovery_snapshots')
    op.drop_table('recovery_snapshots')
    op.drop_index(op.f('ix_recovery_checkins_user_id'), table_name='recovery_checkins')
    op.drop_table('recovery_checkins')
    op.drop_index(op.f('ix_recordings_user_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_peer_matches_user_id'), table_name='peer_matches')
    op.drop_table('peer_matches')
    op.drop_index(op.f('ix_patient_conditions_user_id'), table_name='patient_conditions')
    op.drop_table('patient_conditions')
    op.drop_index(op.f('ix_patient_allergies_user_id'), table_name='patient_allergies')
    op.drop_table('patient_allergies')
    op.drop_index(op.f('ix_onboarding_progress_user_id'), table_name='onboarding_progress')
    op.drop_table('onboarding_progress')
    op.drop_index(op.f('ix_nutrition_logs_user_id'), table_name='nutrition_logs')
    op.drop_table('nutrition_logs')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_mobilisation_milestones_user_id'), table_name='mobilisation_milestones')
    op.drop_table('mobilisation_milestones')
    op.drop_index(op.f('ix_message_threads_patient_id'), table_name='message_threads')
    op.drop_table('message_threads')
    op.drop_table('message_templates')
    op.drop_index(op.f('ix_medications_user_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_journey_phases_user_id'), table_name='journey_phases')
    op.drop_table('journey_phases')
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_habit_logs_user_id'), table_name='habit_logs')
    op.drop_table('habit_logs')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_eras_progress_user_id'), table_name='eras_progress')
    op.drop_table('eras_progress')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_data_requests_user_id'), table_name='data_requests')
    op.drop_table('data_requests')
    op.drop_index(op.f('ix_content_progress_user_id'), table_name='content_progress')
    op.drop_index(op.f('ix_content_progress_content_id'), table_name='content_progress')
    op.drop_table('content_progress')
    op.drop_index(op.f('ix_consent_log_user_id'), table_name='consent_log')
    op.drop_table('consent_log')
    op.drop_index(op.f('ix_clinician_assignments_patient_id'), table_name='clinician_assignments')
    op.drop_index(op.f('ix_clinician_assignments_clinician_id'), table_name='clinician_assignments')
    op.drop_table('clinician_assignments')
    op.drop_index(op.f('ix_clinical_scores_user_id'), table_name='clinical_scores')
    op.drop_table('clinical_scores')
    op.drop_index(op.f('ix_cessation_tracking_user_id'), table_name='cessation_tracking')
    op.drop_table('cessation_tracking')
    op.drop_index(op.f('ix_carer_links_patient_id'), table_name='carer_links')
    op.drop_index(op.f('ix_carer_links_invite_token'), table_name='carer_links')
    op.drop_index(op.f('ix_carer_links_carer_id'), table_name='carer_links')
    op.drop_table('carer_links')
    op.drop_index(op.f('ix_breathing_sessions_user_id'), table_name='breathing_sessions')
    op.drop_table('breathing_sessions')
    op.drop_index(op.f('ix_audit_log_patient_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_appointments_user_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_alerts_patient_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_quiz_questions_quiz_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_table('quizzes')
    op.drop_table('hospitals')
    op.drop_table('education_content')
    op.drop_table('badges')
    # ### end Alembic commands ###
